spring.application.name=jpa-demo

# 1. Kết nối SQL Server
# Lưu ý: Thay 'Ten_Database' bằng tên DB bạn đã tạo trong SSMS
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=jpa-demo;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123

# 2. Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto=update: Tự động tạo bảng nếu chưa có, hoặc cập nhật bảng nếu có thay đổi (Không xóa dữ liệu cũ)
# ddl-auto=create: Xóa sạch bảng cũ và tạo lại bảng mới mỗi khi restart app
spring.jpa.hibernate.ddl-auto=update

# Quy định kiểu phương ngôn của SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect